{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "servicetest" %}
# The name above should match the one in setup.py
package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: BSD 3-Clause License
  license_family: BSD


source:
  path: ..

build:
  noarch: python
  script: python setup.py install --record=record.txt
  preserve_egg_dir: True

requirements:
  build:
    - python

outputs:
  - name: {{ name|lower }}

extra:
  recipe-maintainers:
    - rohitkhattar
